backend:
  ### enable below lines for github integration ###
  name: github
  repo: 1st-Chertsey-Scout-Group/content
  branch: main
media_folder: "_assets/images"
public_folder: "/static/img"
publish_mode: editorial_workflow
squash_merges: true
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - label: "News"
    name: "news"
    folder: "news"
    create: true
    editor:
      preview: false
    slug: "{{year}}_{{month}}_{{day}}_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Abbey","Achievements","AGM","Beavers","Black Cherry Fair","Bourne","Camp","Canoeing","Comedy Night","Community","Competition","Cooking","Cubs","Donation","Dons","Explorers","Fireworks","Fishing","Football","Fundraiser","Hunters","Jamboree","Lost Property","New HQ","Parade","Programme","Recruitment","Remembrance","Scouts","Squirrels","Uniform","Website","World War"]